### ISSUE TITLE
The highlight of keyword from `'preview'` cannot be cleared with `:noh`

### ISSUE THREAD

**Issue by nyngwang** [mrbjarksen/neo-tree-diagnostics.nvim#16]
This continued #14.

> @mrbjarksen Yes, I just tried the mapping `['<cr>'] = 'preview'` and it works like my `no_open` above. Could you elaborate more on how to make this "preview" mode behavior enabled by default, so I don't have to use a mapping to enable it? ([link to it](https://github.com/mrbjarksen/neo-tree-diagnostics.nvim/issues/14#issuecomment-1258824072))

Now I can preview entries from the diagnostics list with `<CR>`, but a new problem appeared: the word (ex. the `NOREF_NOERR` in the image below) still got highlighted after calling `:noh`, which I consider as a bug. What's the problem in this case?

<img src="https://user-images.githubusercontent.com/24765272/192443785-00c09b75-bc2f-4526-83bf-342d2c3d7bb3.png" width="500">

**Comment by nyngwang** [comment]
> [...] Leaving the neo-tree buffer also disables the preview automatically. [...]

It seems that this is not my case. I did change back to use `open` as my previous issue (and you since you have suggested).

> [...] There's no command I know of currently that will disable the preview mode but keep the preview window [...]  If this is what you're looking for [...]

No. my imagination of "follow" is that the targeted buffer gets changed when my cursor is moving through the item list. (this is the reverse of the "targeted buffer" to the "vertical cursorline" on the neo-tree drawer.

**Comment by mrbjarksen** [comment]
> For me, this is not intuitive and can be reported to the source. (I will do it later)

The problem is that `nvim_buf_add_highlight` can apply highlights arbitrarily while `hlsearch` only applies to text which has been searched (using `/` or `:s`, for example). It wouldn't make sense to clear all buffer highlights when clearing search highlights.

> It seems that this is not my case. I did change back to use open as my previous issue (and you since you have suggested).

Interesting, it works on my end. What behavior are you seeing?

>  My imagination of "follow" is that the targeted buffer gets changed when my cursor is moving through the diagnostic item list.

The option `follow_current_file` is named in accordance with neo-tree's base sources, where the option changes the focus in the source based on the file/buffer which is currently in use.
