### ISSUE TITLE
`reveal` does not respect `follow_behavior`

### ISSUE THREAD

**Issue by mrbjarksen** [mrbjarksen/neo-tree-diagnostics.nvim#19]
Using `:Neotree diagnostics reveal` always focuses the file, for example, even if `follow_behavior.always_follow_file` is `false`. This should be a simple fix, but maybe reveal behavior should be separate from follow behavior?

**Comment by cseickel** [comment]
> Using `:Neotree diagnostics reveal` always focuses the file

That is the purpose of `reveal`, to find and focus the file.

`always_follow_file` can be thought of as an automatic reveal, like the difference between `preview` and `toggle_preview`.

**Comment by mrbjarksen** [comment]
@cseickel Yes, I realize that. The problem (or rather slight inconvenience) for me is that I use a keybinding for `:Neotree diagnostics reveal bottom` for both opening the diagnostics source and focusing it while it is already opened. This means that if I open a diagnostic and then return to the source to go to the next diagnostic, I have to navigate down again.

I'm considering adding an option `follow_on_reveal` or similar to work around this, but if you object because of the conceptual difference between follow and reveal, I don't mind dropping it.

**Comment by cseickel** [comment]
I think I understand now. Is the problem that it is focusing you on the file itself, instead of returning you to the child node which was the last diagnostic you had focused?

If that's the issue, then I would just change your implementation of `always_follow_file` and `reveal` to not change the focus if the current node is a diagnostic which is a child node of the target file.

**Comment by mrbjarksen** [comment]
Fixed as of 9a78e75.
